server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL 驱动包 com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: MYXH
    password: 520.ILY!

mybatis:
  mapperLocations: classpath:mapper/*.xml
  # 所有 Entity 类所在的包
  type-aliases-package: com.myxh.springcloud.entities
